name: Run tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

concurrency:
  group: run-tests-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"] 
        node: [22]

    name: ${{ matrix.os }}_node${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: badisi/actions/setup@v2
        with:
          node-version: ${{ matrix.node }}
          setup-chrome: true

      - name: Build tests application
        working-directory: projects/tests-app
        run: npm run build

      - name: Serve tests application
        working-directory: dist/tests-app
        shell: bash # use bash because powershell is used by default on Windows and background job are cleaned after the run
        # use global install (instead of npx) because otherwise the server won't stay up on Windows
        run: |
          npm install -g http-server
          http-server --port=4200 &

      - name: Make sure tests application is running
        shell: bash # use bash so that sleep is recognized even on Windows
        run: sleep 5 && curl http://localhost:4200 -I

      - name: Run tests
        working-directory: projects/tests-e2e
        run: npm run start -- --watch=false --debug=true --headless=true
