name: CI tests

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  pull_request:
  workflow_dispatch:

jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm clean-install
      - name: Serve tests application
        run: |
          npx ng serve --configuration=production &
          sleep 5 &&
          curl http://localhost:4200 -I
      - name: Run tests
        run: npm run test -- --debug=true --headless=true --watch=false
